spring:
  rabbitmq:
    host: 127.0.0.1   #主机名
    port: 5672 #端口
    virtual-host: /  #虚拟主机
    username: guest  #用户名
    password: guest  #密码
    listener:
      simple:
        prefetch: 1  #每次都取一条，处理完成才能获取下一个消息
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS