server:
  port: 80

eureka:
  client:
    register-with-eureka: false  #表示是否将自己注册进eurekaserver默认是true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eurek

#openFeign超时控制 默认是1秒
ribbon:
  ReadTimeout: 5000      #读取资源时间
  ConnectTimeout: 5000   #建立链接时间

logging:
  level:
    #feign日志以什么级别监控那个接口
    com.xiangfei.springcloud.service.PaymentFeignService: debug