server:
  port: 80

eureka:
  client:
    register-with-eureka: true  #表示是否将自己注册进eurekaserver默认是true
    fetch-registry: true        #表示是否从eurekaserver抓取自己已有的注册信息默认是true
    service-url:
      defaultZone: http://localhost:7001/eureka

spring:
  application:
    name: cloud-order-service